# List of skills for matching (can be extended)
SKILLS = [
    'python', 'docker', 'machine learning', 'fastapi', 'aws', 'nlp',
    'tensorflow', 'pytorch', 'scikit-learn', 'pandas', 'numpy', 'matplotlib',
    'seaborn', 'sql', 'nosql', 'mongodb', 'postgresql', 'redis', 'git',
    'github', 'gitlab', 'ci/cd', 'jenkins', 'travis ci', 'github actions',
    'aws s3', 'aws ec2', 'aws rds', 'aws lambda', 'aws dynamodb',
    'kubernetes', 'docker-compose', 'api development', 'restful apis',
    'graphql', 'microservices', 'data analysis', 'data visualization',
    'big data', 'spark', 'hadoop', 'kafka', 'etl', 'data warehousing',
    'cloud computing', 'azure', 'gcp', 'deep learning', 'neural networks',
    'computer vision', 'object detection', 'image processing',
    'natural language processing', 'sentiment analysis', 'topic modeling',
    'transformers', 'bert', 'gpt', 'time series analysis',
    'statistical modeling', 'a/b testing', 'model deployment', 'mlops',
    'airflow', 'prefect', 'dvc', 'mlflow', 'unit testing',
    'integration testing', 'system design', 'agile', 'scrum', 'linux',
    'bash', 'shell scripting', 'virtualization', 'vmware', 'virtualbox',
    'containerization', 'terraform', 'ansible', 'puppet', 'chef',
    'javascript', 'html', 'css', 'react', 'angular', 'vue.js', 'node.js',
    'django', 'flask', 'ruby on rails', 'java', 'c++', 'c#', 'go', 'scala',
    'r', 'excel', 'google sheets', 'tableau', 'power bi', 'spark streaming',
    'hadoop hdfs', 'yarn', 'zookeeper', 'cassandra', 'neo4j', 'rabbitmq',
    'aws eks', 'aws ecr', 'azure aks', 'gcp gke', 'openshift', 'helm',
    'prometheus', 'grafana', 'elasticsearch', 'logstash', 'kibana',
    'serverless', 'aws step functions', 'azure functions', 'gcp cloud functions',
    'blockchain', 'smart contracts', 'solidity', 'web3', 'cybersecurity',
    'network security', 'penetration testing', 'ethical hacking', 'cryptography',
    'devops', 'site reliability engineering', 'sre', 'monitoring', 'logging',
    'incident response', 'disaster recovery', 'business intelligence',
    'data mining', 'feature engineering', 'model evaluation', 'model selection',
    'hyperparameter tuning', 'cross-validation', 'regularization', 'boosting',
    'bagging', 'random forests', 'support vector machines', 'k-means',
    'dbscan', 'hierarchical clustering', 'pca', 't-sne', 'umap', 'recommender systems',
    'reinforcement learning', 'gan', 'autoencoders', 'lstm', 'gru',
    'convolutional neural networks', 'cnn', 'recurrent neural networks', 'rnn',
    'transfer learning', 'fine-tuning', 'attention mechanisms', 'transformers',
    'federated learning', 'differential privacy', 'explainable ai', 'xai',
    'responsible ai', 'ai ethics', 'fairness', 'bias detection', 'bias mitigation',
    'ai governance', 'regulatory compliance', 'gdpr', 'ccpa', 'project management',
    'leadership', 'communication', 'collaboration', 'problem solving',
    'critical thinking', 'adaptability', 'continuous learning', 'mentoring',
    'technical writing', 'presentation skills'
]
